### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by seetch** [iTXTech/SimpleFramework#1]
What is error? PHP Fatal error:  Class 'Threaded' not found in phar:///home/seetch/web/site.my/www/SimpleFrameworkCLI_1.1.0.phar/src/sf/util/ClassLoader.php on line 17

**Comment by seetch** [comment]
`class ClassLoader extends \Threaded` What is Threaded? :)

**Comment by seetch** [comment]
I understand everything, class not ready, i, help?

**Comment by PeratX** [comment]
This program should be executed in Command Line, not in web.
Besides,it needs php Thread Safe with pthreads extension.
